version: '3.3'

services:
  server:
    build:
      dockerfile: ./Dockerfile
      context: . 
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
    - ./:/code:cached
    # user: "${CURRENT_UID}"